### ISSUE TITLE
Please clear the url when creating a new tab

### ISSUE THREAD

**Issue by vicelus** [rharel/webext-new-tab-tweaker#17]
It's a minor issue, since the main point of this add is to tweak the image on the tab (like Chrome). But it's a nuisance that everytime i create a new tab, my url creates this "moz-extension://07434bd5-7af1-450e-868b-8de3dc188090/url_overrides/newtab/page.html" in which i have to manually click and select all the lenght of the url and type what i want and/or delete it. Fixing this would make this add-on 5* for me.

**Comment by rharel** [comment]
This is not something under the control of WebExtensions, so there is nothing I can do about it unfortunately. This needs to be fixed in Firefox itself, and in fact **it is already fixed** in the most recent _beta_ version of Firefox 57.  Either install that or wait patiently until the fix makes it to the release channel.

**Comment by rharel** [comment]
Oh I almost forgot, to ease your pain you could use the keyboard shortcut Ctrl+L (on Windows at least, I'm not sure if it is the same for Mac or Linux). This selects the address bar.

**Comment by Smile4ever** [comment]
On Linux it's Ctrl+L as well. On macOS it's probably Command+L.
